/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.employeepayroll.tester;

import org.junit.Test;

import static org.junit.Assert.*;

public class PayrollTest {

}
