/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.employeepayroll.tester;

import org.junit.Test;

import com.blz.employeepayroll.controller.PayrollService;
import com.blz.employeepayroll.controller.PayrollService.IOService;
import com.blz.employeepayroll.model.EmployeePayrollData;

import junit.framework.Assert;

import java.util.Arrays;

@SuppressWarnings("deprecation")
public class PayrollTest {
	@Test
	public void given3EmployeesWhenWrittenToFileShouldMatchEmployeesEntries() {
		EmployeePayrollData[] arrayOfEmps = { new EmployeePayrollData(1, 25000.56, "Devnandan Kumar"),
				new EmployeePayrollData(2, 15000.65, "Manoj Kumar"),
				new EmployeePayrollData(3, 22000.67, "Abhishek sinha") };
		PayrollService payrollService;
		payrollService = new PayrollService(Arrays.asList(arrayOfEmps));
		payrollService.write(IOService.FILE_IO);
		long entriesCount=payrollService.countEntries(IOService.FILE_IO);
		payrollService.printData(IOService.FILE_IO);
		Assert.assertEquals(3, entriesCount);
	}
	
	@Test
	public void givenFileOnReadingFromFileShouldMatchEmployeeCount() {
		PayrollService payrollService=new PayrollService();
		long entries=payrollService.readEmployeeData(IOService.FILE_IO);
	}

}
