/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.employeepayroll.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import com.blz.employeepayroll.model.EmployeePayrollData;
import com.blz.employeepayroll.model.EmployeePayrollFileIOService;

public class PayrollService {
	public enum IOService {
		CONSOLE_IO, FILE_IO, DB_IO, REST_IO;
	}

	private List<EmployeePayrollData> employeePayrollList;

	public PayrollService() {

	}

	// Constructor
	public PayrollService(List<EmployeePayrollData> employeePayrollList) {
		this.employeePayrollList = employeePayrollList;
	}

	// Method to print data back to console or file or DB
	public void write(IOService ioService) {
		if (ioService.equals(ioService.CONSOLE_IO))
			System.out.println("Given Employee Data is : " + employeePayrollList);
		else if (ioService.equals(ioService.FILE_IO))
			new EmployeePayrollFileIOService().writeData(employeePayrollList);
	}

	// Method to take data from console
	private void readEmployeeData(Scanner SC) {
		System.out.println("Enter your name : ");
		String name = SC.nextLine();
		System.out.println("Enter your ID : ");
		int id = SC.nextInt();
		System.out.println("Enter your salary : ");
		double salary = SC.nextDouble();
		EmployeePayrollData empData = new EmployeePayrollData(id, salary, name);
		employeePayrollList.add(empData);
	}

	// Counting total number of entries into the payroll list
	public long countEntries(IOService fileIo) {
		return new EmployeePayrollFileIOService().countEntries(employeePayrollList);
	}

	// Printing all the entries of PayrollList
	public void printData(IOService fileIo) {
		if (fileIo.equals(IOService.FILE_IO))
			new EmployeePayrollFileIOService().printData((employeePayrollList));
	}

	// Reading the employee payroll list so that we can do any operation
	public long readEmployeeData(IOService fileIo) {
		List<String> list=new ArrayList<>();
		if (fileIo.equals(IOService.FILE_IO))
			list = new EmployeePayrollFileIOService().readData();
		return list.size();
	}

	// Main method to control the flow of execution
	public static void main(String[] args) {
		Scanner SC = new Scanner(System.in);
		ArrayList<EmployeePayrollData> employeePayrollList = new ArrayList<EmployeePayrollData>();

		PayrollService employeePayrollService = new PayrollService(employeePayrollList);
		employeePayrollService.readEmployeeData(SC);
		employeePayrollService.write(IOService.CONSOLE_IO);

	}
}
