/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.blz.employeepayroll.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import com.blz.employeepayroll.model.EmployeePayrollData;

public class PayrollService {
	private List<EmployeePayrollData> employeePayrollList;

	public PayrollService() {

	}

	//Constructor
	public PayrollService(List<EmployeePayrollData> employeePayrollList) {
		this.employeePayrollList = employeePayrollList;
	}

	//Method to print data back to console
	private void write() {
		System.out.println("Given Employee Data is : " + employeePayrollList);
	}

	//Method to take data from console
	private void readEmployeeData(Scanner SC) {
		System.out.println("Enter your name : ");
		String name = SC.nextLine();
		System.out.println("Enter your ID : ");
		int id = SC.nextInt();
		System.out.println("Enter your salary : ");
		double salary = SC.nextDouble();
		EmployeePayrollData empData = new EmployeePayrollData(id, salary, name);
		employeePayrollList.add(empData);
	}

	//MAin method to control the flow of execution
	public static void main(String[] args) {
		Scanner SC = new Scanner(System.in);
		ArrayList<EmployeePayrollData> employeePayrollList = new ArrayList<EmployeePayrollData>();

		PayrollService employeePayrollService = new PayrollService(employeePayrollList);
		employeePayrollService.readEmployeeData(SC);
		employeePayrollService.write();

	}
}
